## Topics
# topic_imu: "/vn100/imu"
# topic_baro_altimeter: "/sensor_platform/baro"
topic_radar_trigger: "/sensor_platform/radar_left/trigger"
topic_radar_scan: "/radar/left/cloud"

## Extrinsic calibration of body frame to radar frame
# translation of radar frame expressed in body frame
l_b_r_x:  0.07359
l_b_r_y:  0.04761
l_b_r_z: -0.16259

# rotation radar frame to body frame
q_b_r_x:  0
q_b_r_y:  0
q_b_r_z:  -0.5372996
q_b_r_w:  0.8433914

# length of each radar frame (="exposure time" of radar scan) in milliseconds
radar_frame_ms: 18.5

# nominal radar rate
radar_rate: 10.0 # 10.526315789
