## Topics
# topic_imu: "/vn100/imu"
# topic_baro_altimeter: "/sensor_platform/baro"
topic_radar_trigger: "/sensor_platform/radar_left/trigger"
topic_radar_scan: "/ti_mmwave/radar_scan_pcl_0"

## Extrinsic calibration of body frame to radar frame
# translation of radar frame expressed in body frame
l_b_r_x: 0.04222
l_b_r_y: -0.00973
l_b_r_z: -0.14915

# rotation radar frame to body frame
# q_b_r_x: 0.0
# q_b_r_y: 0.131
# q_b_r_z: 0.0
# q_b_r_w: 0.991
q_b_r_x: -0.093 # 0.0
q_b_r_y:  0.093 # 0.131
q_b_r_z: -0.701 # 0.0
q_b_r_w:  0.701 # 0.991

# length of each radar frame (="exposure time" of radar scan) in milliseconds
radar_frame_ms: 6.4139

# nominal radar rate
radar_rate: 10.0
