## Topics
# topic_imu: "/vn100/imu"
# topic_baro_altimeter: "/sensor_platform/baro"
topic_radar_trigger: "/sensor_platform/radar_left/trigger"
topic_radar_scan: "/radar/middle/cloud"

## Extrinsic calibration of body frame to radar frame
# translation of radar frame expressed in body frame
l_b_r_x:  0.06841
l_b_r_y:  0.01482
l_b_r_z: -0.13265

# rotation radar frame to body frame
q_b_r_x:  0.707
q_b_r_y:  0.707
q_b_r_z:  0.0
q_b_r_w:  0.0

# length of each radar frame (="exposure time" of radar scan) in milliseconds
radar_frame_ms: 4.138

# nominal radar rate
radar_rate: 10.0 # 10.526315789